# Netlify Configuration for Ultimate AI-Powered Creator Platform

[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish (Vite builds to 'dist')
  publish = "dist"
  
  # Node.js version
  environment = { NODE_VERSION = "18" }

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # CORS headers for API access
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (these will be set in Netlify dashboard)
# Don't put actual values here - this is just documentation
[build.environment]
  # These should be set in Netlify dashboard under Site Settings > Environment Variables
  # VITE_SUPABASE_URL = "your_supabase_url"
  # VITE_SUPABASE_ANON_KEY = "your_supabase_anon_key"
  # VITE_REVENUECAT_PUBLIC_KEY = "your_revenuecat_public_key"
  # VITE_ALGORAND_NODE_URL = "https://testnet-api.algonode.cloud"
  # VITE_TAVUS_API_KEY = "your_tavus_api_key"
  # VITE_ELEVENLABS_API_KEY = "your_elevenlabs_api_key"
  # VITE_REDDIT_CLIENT_ID = "your_reddit_client_id"

# Functions configuration (if using Netlify Functions)
[functions]
  directory = "netlify/functions"

# Form handling (if using Netlify Forms)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Custom domain configuration (replace with your IONOS domain)
# This will be configured in Netlify dashboard under Domain Management
# [[redirects]]
#   from = "https://www.yourdomain.com/*"
#   to = "https://yourdomain.com/:splat"
#   status = 301
#   force = true